name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout Code
        uses: actions/checkout@v3

      # 设置 Go 环境
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20 # 替换为你的 Go 版本

      # 安装依赖并编译
      - name: Install Dependencies and Build
        run: |
          go mod tidy
          go build -o app .

      # 设置版本号
      - name: Set Version Tag
        id: vars
        run: echo "TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      # 登录 DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 构建 Docker 镜像
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/test-task:${{ env.TAG }} .

      # 推送 Docker 镜像
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/test-task:${{ env.TAG }}