name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout Code
        uses: actions/checkout@v4

      # 设置 Go 环境
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20' # 替换为你的 Go 版本

      # 安装依赖并编译
      - name: Install Dependencies and Build
        run: |
          go mod tidy
          go build -o app .

      # 设置版本号
      - name: Set Version Tag
        id: vars
        run: |
          echo "TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
          echo "LATEST=latest" >> $GITHUB_ENV

      # 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 登录 DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 构建 Docker 镜像
      - name: Build and Push Multi-Arch Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag ${{ vars.DOCKERHUB_USERNAME }}/test-task:${{ env.TAG }} \
            --tag ${{ vars.DOCKERHUB_USERNAME }}/test-task:${{ env.LATEST }} \
            --push .
